apiVersion: batch/v1
kind: Job
metadata:
  name: selenium-test-job
spec:
  template:
    spec:
      containers:
        - name: selenium
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
      restartPolicy: Never
  backoffLimit: 0
